include:
  - project: 'infra/ci-cd-templates'
    file:
      - '/php_matrix.gitlab-ci.yml'

stages:
  - test
  - analyse

before_script:
  - apt-get update
  - composer config -g gitlab-domains gitlab.com ${CI_SERVER_HOST}
  - composer config -g http-basic.${CI_SERVER_HOST} gitlab-ci-token "${CI_JOB_TOKEN}"
  - composer config -g gitlab-protocol https
  - composer config -g --auth http-basic.repo.packagist.com token "${CI_COMPOSER_TOKEN}"

test:
  stage: test
  extends: .php_matrix
  parallel:
    matrix:
      - PHP_VERSION: [ '8.3', '8.4', '8.5' ]
        PHP_EXTENSIONS: 'intl mbstring gd'
        STABILITY: [ 'prefer-lowest', 'prefer-stable' ]
  script:
    - composer run test

analyse:
  stage: analyse
  extends: .php_matrix
  parallel:
    matrix:
      - PHP_VERSION: [ '8.3', '8.4', '8.5' ]
        PHP_EXTENSIONS: 'intl mbstring gd'
        STABILITY: [ 'prefer-stable' ]
  script:
    - composer run analyse
